resource "local_file" "inventory" {
  content = <<-DOC
    # Ansible inventory containing variable values from Terraform.
    # Generated by Terraform.

    [all]
    node01.netology.yc ansible_host=${yandex_compute_instance.public-vm.network_interface.0.nat_ip_address} ansible_user=centos
    DOC
  filename = "../ansible/inventory"

  depends_on = [
    yandex_compute_instance.public-vm
  ]
}
