resource "local_file" "inventory" {
  content = <<-DOC
    # Ansible inventory containing variable values from Terraform.
    # Generated by Terraform.

    [all]
    node01.netology.yc ansible_host=${yandex_compute_instance.public-vm.network_interface.0.nat_ip_address} ansible_user=centos
    DOC
  filename = "../ansible/inventory"

  depends_on = [
    yandex_compute_instance.public-vm
  ]
}

resource "null_resource" "get_inventory" {
  provisioner "local-exec" {
    command = "cat ../ansible/inventory && cat ~/.ssh/id_rsa.pub"
  }

  depends_on = [
    local_file.inventory
  ]

  triggers = {
      inventory_ip_addresses = yandex_compute_instance.public-vm.network_interface.0.nat_ip_address
  }
}