---
apiVersion: v1
kind: Service
metadata:
  annotations:
  labels:
    app: wonder-app
    release: {{ .Release.Name }}
  name: "wonder-app-{{ .Release.Name }}"
spec:
  ports:
    - name: "http"
      port: 80
      targetPort: http
      nodePort: 30880
  selector:
    app: wonder-app
    release: {{ .Release.Name }}
  type: NodePort